name: Deploy Stayhub

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync project files
        run: |
          rsync -av --exclude='.env' ./ ~/Stayhub-runner/_work/Stayhub/Stayhub/

      - name: Install dependencies
        run: |
          cd ~/wanderlust-runner/Stayhub
          npm install

      - name: Restart server
        run: pm2 restart stayhub
